# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1euyC3ZGUKFS1VCBPWtKNXKNCWkGbQ5qM
"""

import json

with open("products.json","r") as file:
     data = json.load(file)

type(data)

data["name"],data["colors"],

name=data["name"];colors=data["colors"]

name,colors



data["colors"]

colors=data["colors"]

colors

#pip install requests

import requests

# Send a GET request to a website and get the response
response = requests.get('https://www.example.com')

# Check the content of the response (HTML content in this case)
print("Content:", response.text)

## fetch the content
#data = response.json()

#type(data) # dict

response = requests.get('https://www.example.com')

# Check the status code of the response
print("Status code:", response.status_code)

response=requests.get('https://zucwflxqsxrsmwseehqvjmnx2u0cdigp.lambda-url.ap-south-1.on.aws/mentorskool/v1/sales')
print("Status code:",response.status_code)





